server:
  port: 8070
  servlet:
    context-path: /template
spring:
  security:
    ignored: "/actuator/**"
  application:
    name: template
  jmx:
    enabled: false
keycloak:
  url: http://172.26.155.73:30922
  realm: test
  jwk: ${keycloak.url}/auth/realms/${keycloak.realm}/protocol/openid-connect/certs
prog.matoz.config:
  time-zone: America/Sao_Paulo
loggin:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG